### ISSUE TITLE
Creating a new settings.cfg

### ISSUE THREAD

**Issue by basundhara-g** [JCGoran/coffe#1]
Hi,

I created a copy of and modified the settings.cfg according to my requirement, and I saved it by a different name (say settings1.cfg). But while running the new cfg file, I get the following error: "Cannot read the parameter file."

Do I need to do something to enable the code to read the newly named cfg file? Or only a file named as settings.cfg can be run?

Thanks in advance,
Basundhara

**Comment by JCGoran** [comment]
Solved through internal communication, thus I'm closing the issue.

For possible future readers:
This error arises when the libconfig library is unable to parse the parameter file. There are two possible reasons for this:
1. the syntax of the parameter file is incorrect. To rectify this, please refer to the libconfig [documentation](https://hyperrealm.github.io/libconfig/libconfig_manual.html#Configuration-Files) for proper syntax.
2. the parameter file does not exist in the location the user has specified. Providing a valid path to the parameter file solves this.
